# Generated by Django 3.0.5 on 2020-07-31 12:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0004_auto_20200731_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItalyDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates_array', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
            ],
            options={
                'db_table': 'Italy_dates',
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Dates',
            new_name='LondonDate',
        ),
        migrations.AlterModelTable(
            name='londondate',
            table='London_dates',
        ),
    ]
