# Generated by Django 3.0.5 on 2020-08-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0005_auto_20200731_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='borough',
            name='latest_deaths',
            field=models.IntegerField(default=0),
        ),
    ]
