language: python
python:
  - 3.7
services:
  - postgresql
env:
  global:
    - DATABASE_URL='postgres://postgres@localhost/travis_ci_test'
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - python manage.py test